name = "ExamplePkg"
uuid = "77dfbc7e-2389-4d93-8aeb-078ceb1a4d4d"
authors = ["“SylvieShi403” <“lfs”5712@psu.edu>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Distributions = "0.25.122"
Test = "1.11.0"
